### ISSUE TITLE
Can’t install?

### ISSUE THREAD

**Issue by schlafenszeit** [NoisyFlake/CozyBadges-support#7]
![312E9818-B894-45E8-9C99-B82109DC2E32](https://user-images.githubusercontent.com/66819086/84474158-404e1e80-ac3f-11ea-8616-e9da10baf854.png)
**Bug description:**
Cydia won’t let me install the app due to the attached error. 
**Steps to reproduce this behavior:**
While trying to install through Cydia. 
**Expected behavior:**

**Screenshots:**

**iOS Version:**
13.5
**Device:**
iPhone 11 Pro Max 
**Tweak list:** 
(Attach it as a text file or put it on e.g. pastebin.com)
Lynx, fabric 2, prysm, snowboard, vinyl, gesto
**Additional context:**

**Comment by NoisyFlake** [comment]
Available on BigBoss: http://cydia.saurik.com/package/org.thebigboss.libcolorpicker/
